### ISSUE TITLE
change in pool heat modecauses error in 6.0-DEV

### ISSUE THREAD

**Issue by emes** [tagyoureit/nodejs-poolController#127]
### Expected behavior and actual behavior

for example REST call to /poolheat/mode/1, or app seeing change by others results in an error.

```
15:37:36.000 info: Msg# 230   undefined asking Main to change pool heat mode to OFF (@ 23 degrees) & spa heat mode to OFF (at 35 degrees): [165,1,16,35,136,4,23,35,0,0,1,159]
```

### What is actually happening (screenshots are helpful)

```
12:05:55.000 verbose: Msg# 17130   Main --> Pump 1: Remote control - disable pump control panel: [165,0,96,16,4,1,255,2,25]
12:05:55.000 verbose: Msg# 17131   Pump 1: Remote control -  disable pump control panel: [165,0,16,96,4,1,255,2,25]
12:05:55.000 verbose: Msg# 17132   Main --> Pump 1: Pump power to off: [165,0,96,16,6,1,4,1,32]
12:05:55.000 info: API Response
12:05:55.000 verbose: Msg# 17140   Pool/Spa heat set point changed:  pool heat mode: Heater @ 23 degrees; spa heat mode OFF at 35 degrees
TypeError: currentHeat.whatsDifferent is not a function
    at Object.setHeatModeAndSetPoints (/src/lib/equipment/heat.ts:173:101)
    at Object.process (/src/lib/comms/inbound/controller/8.ts:28:10)
    at Object.processControllerPacket (/src/lib/comms/inbound/process-controller.ts:76:34)
    at decode (/src/lib/comms/inbound/decode-helper.ts:307:45)
    at Object.processChecksum (/src/lib/comms/inbound/decode-helper.ts:363:13)
    at iterateOverArrayOfArrays (/src/lib/comms/inbound/receive-buffer.ts:144:38)
    at Timeout.checkIterate [as _onTimeout] (/src/lib/comms/inbound/receive-buffer.ts:257:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
nodejs-poolController has closed successfully.
```

### Steps to reproduce the problem

Turn on/off pool heat

**Comment by tagyoureit** [comment]
Fixed.  Thanks.
