### ISSUE TITLE
Error:InvalidEquipmentData when setting schedule

### ISSUE THREAD

**Issue by jarrah42** [tagyoureit/nodejs-poolController#303]
When I create a schedule and save it, I get a popup Error:InvalidEquipmentData with the following stack trace:

ApiError: Invalid heat source: null
    at ScheduleCommands.setScheduleAsync (/home/pi/nodejs-poolController/controller/boards/SystemBoard.ts:2635:91)
    at /home/pi/nodejs-poolController/web/services/config/Config.ts:523:55
    at Layer.handle [as handle_request] (/home/pi/nodejs-poolController/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/nodejs-poolController/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/nodejs-poolController/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/nodejs-poolController/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:275:10)
    at /home/pi/nodejs-poolController/web/Server.ts:377:25
    at Layer.handle [as handle_request] (/home/pi/nodejs-poolController/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:275:10)
    at /home/pi/nodejs-poolController/node_modules/body-parser/lib/read.js:130:5

**Pool Equipment**
 - Controller: Nixie Single Body
 - Pump(s) manufacturer and model: IntelliFlow VS
 - Chlorinator: iChlor

**Comment by jarrah42** [comment]
The latest changes fixed this problem, thanks! I found a workaround in any case. If you select the pool circuit, then pick Heat Source: off, then go back to a feature the error goes away.
