### ISSUE TITLE
4.1 Startup trouble

### ISSUE THREAD

**Issue by darkhelmet7** [tagyoureit/nodejs-poolController#58]
Just downloaded the new 4.1 Dev and get the following error on startup.

Exited nodejs-poolController cleanly
module.js:471
    throw err;
    ^

Error: Cannot find module 'serialport'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at GenericProvider.$get (/home/pi/Downloads/nodejs-poolController/src/lib/app.js:56:12)
    at Object.getService (/home/pi/Downloads/nodejs-poolController/node_modules/bottlejs/dist/bottle.js:368:89)
    at Object.init (/home/pi/Downloads/nodejs-poolController/src/lib/comms/sp-helper.js:28:39)
    at Object.exports.init (/home/pi/Downloads/nodejs-poolController/src/lib/app.js:169:25)
    at Object.<anonymous> (/home/pi/Downloads/nodejs-poolController/src/index.js:25:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)

I can switch back to my 4.0 install and it works well.

**Comment by tagyoureit** [comment]
Hmmm, that's weird.  Some of the dependencies went missing.  Maybe Snyk took them out??  I put them back in (I hope I got all of them).  I'll close this for now, but open again if it still has problems.  Thx for pointing this out.
